import { Project } from "@/data/index.ts";

// Project data
export const projects: Project[] = [
    {
        id: "1",
        title: "Cloven Blade",
        technologies: [
            "Unreal Engine 5",
            "C++",
            "GAS",
            "Jira",
            "Confluence",
            "GitHub",
            "Perforce",
        ],

        shortDescription:
            "A side-scrolling beat 'em up vertical slice developed at Ballistic Pork, where I served as Primary Gameplay Programmer and Scrum Master.",

        role: [
            "Primary Gameplay Programmer",
            "Scrum Master",
        ],

        teamSize: "Approximately 6 developers",

        overview:
            "Cloven Blade is a side-scrolling beat 'em up vertical slice developed in Unreal Engine 5. As Primary Gameplay Programmer, I owned the implementation of the project's gameplay layer in C++, translating gameplay design requirements into scalable technical systems while integrating animation, audio, physics, UI, AI, and Gameplay Ability System functionality. Alongside gameplay programming, I also served as Scrum Master throughout development.",

        keyTakeaways: [
            "C++ Gameplay Programming",
            "Gameplay Ability System",
            "Gameplay Architecture",
            "AI Programming",
            "Developer Tooling",
        ],

        systemsImplemented: [
            "Character controller including movement, jumping, coyote jump, dashing, hook mechanics, wall running, wall jumping, wall dashing, and edge grabbing",
            "Combat systems including attacks, combos, weapons, gameplay abilities, invincibility, and immunity",
            "Enemy AI including patrol, combat, attack behaviour, ranged enemies, upper-body aiming, and gameplay object interactions",
            "Gameplay Ability System integration",
            "Inventory system with reusable item objects",
            "Interactables including pickups, hiding barrels, smoke bombs, and shurikens",
            "Gameplay collision and combat state management",
            "Animation, audio, physics, particle effect, and UI integration",
            "Developer tooling for animation-driven gameplay events",
        ],

        technicalHighlights: [
            {
                title: "Gameplay Systems",
                description:
                    "Owned the implementation of the gameplay layer in C++, translating gameplay design requirements into scalable technical systems. Implemented player mechanics, combat, AI, Gameplay Ability System integration, interactables, inventory, gameplay state management, and reusable gameplay frameworks while supporting rapid iteration throughout development.",
            },
            {
                title: "Character Movement Systems",
                description:
                    "Implemented a modular character controller supporting movement, jumping, coyote jump, dashing, hook mechanics, wall running, wall jumping, wall dashing, and edge grabbing. Solved gameplay edge cases such as preventing infinite wall jumps while maintaining responsive player controls.",
            },
            {
                title: "Template Method Pattern",
                description:
                    "Implemented shared character behaviour through a common base character class while allowing derived character types to customize specific gameplay actions through inheritance. This provided a consistent gameplay flow while making it straightforward to extend the system with new player and AI behaviours.",
            },
            {
                title: "Observer Pattern",
                description:
                    "Implemented event-driven communication between reusable gameplay components to reduce coupling and allow gameplay systems to react to state changes without direct dependencies.",
            },
            {
                title: "Object Pool Pattern",
                description:
                    "Implemented object pooling for inventory items by recycling object instances instead of repeatedly allocating and destroying them, reducing runtime allocations while providing a reusable foundation for gameplay objects.",
            },
            {
                title: "Animation-driven Gameplay Framework",
                description:
                    "Developed reusable animation tooling that enabled gameplay effects and abilities to be activated and deactivated through configurable animation frame windows. Gameplay events generated by these windows could also be observed independently by other gameplay systems through event-driven communication, providing a flexible foundation for attacks, hit detection, invincibility, abilities, and other time-sensitive gameplay mechanics.",
            },
            {
                title: "Gameplay System Integration",
                description:
                    "Integrated artist-created animations, audio, UI, particle effects, and gameplay assets into Unreal Engine, ensuring new content functioned correctly within gameplay systems while collaborating closely with artists and designers throughout development.",
            },
        ],

        technicalChallenges: [
            {
                challenge: "Multiple project restarts and changing technical direction",
                solution:
                    "The project was restarted several times and transitioned from a pure C++ architecture to Lyra before ultimately adopting a Gameplay Ability System-based solution. I continuously adapted and reimplemented gameplay systems to support the project's evolving technical direction while maintaining development momentum.",
                result:
                    "Despite multiple architectural changes, the team successfully delivered the vertical slice with a maintainable gameplay framework that supported continued feature development.",
            },
            {
                challenge: "Supporting complex gameplay interactions",
                solution:
                    "Designed and implemented gameplay state handling for collisions, invincibility, immunity, AI interactions, animation timing, and movement edge cases while developing reusable tooling for animation-driven gameplay events.",
                result:
                    "Gameplay systems behaved consistently across a wide variety of combat and movement scenarios while reducing repetitive implementation work and improving iteration speed during development.",
            },
        ],

        additionalResponsibilities: [
            "Served as Scrum Master throughout development, facilitating daily stand-ups, sprint planning, and production tracking in Jira.",
            "Coordinated communication between programmers, artists, designers, management, and external consultants.",
            "Integrated artist-created animations, audio, UI, particle effects, and environment assets into gameplay systems.",
            "Helped maintain team alignment and delivery throughout multiple project restarts and changing technical direction.",
        ],
        images: {
            main: 'https://impro.usercontent.one/appid/oneComWsb/domain/ballisticpork.se/media/ballisticpork.se/onewebmedia/banner_clovenblade_hamlet_01.png?etag=W%2F%22745ba-678b87d4%22&sourceContentType=image%2Fpng&ignoreAspectRatio&resize=1178%2B578',
            gallery: [            ],
        },
        // videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    },
    {
        id: "2",
        title: "Horpus",
        technologies: ["Unreal Engine 5", "Blueprints", "Jira", "GitHub"],
        shortDescription: "A cute horror prototype focused on stealth gameplay, cat AI behaviour, and interactable hiding systems.",
        role: ["Gameplay Programmer"],
        overview: "Horpus is a cute horror prototype built in Unreal Engine 5 using Blueprints. As Gameplay Programmer, I focused on the cat AI, player stealth mechanics, interactable hiding and lure systems, and the environment supporting the prototype's stealth gameplay loop.",
        keyTakeaways: [
            "AI Behaviour",
            "Stealth Gameplay",
            "Interactable Systems",
            "Blueprints",
            "Level Design"
        ],
        systemsImplemented: [
            "Cat AI behaviour including investigation, pursuit, and player tracking",
            "Door interaction logic for AI, including opening doors when investigating the player or following player movement",
            "Sound-based detection for player footsteps when doors are open",
            "Breathing detection based on proximity and line-of-sight limitations",
            "Player stealth mechanics including crouching, holding breath, sneak level, and equipment-based sound modifiers",
            "Dynamic hiding interactions",
            "Interactable lure system using catnip to redirect AI priority",
            "Level layout and environment setup for the prototype"
        ],
        technicalHighlights: [
            {
                title: "AI Behaviour System",
                description: "Implemented cat AI behaviour that could investigate the player's location, react to player movement, open doors, and transition between detection and pursuit behaviours."
            },
            {
                title: "Sound-based Detection",
                description: "Built stealth detection logic where the AI could hear player footsteps depending on environmental conditions, such as whether a door was left open."
            },
            {
                title: "Proximity-based Breathing Detection",
                description: "Implemented breathing detection where the AI could detect the player at close range while respecting walls and spatial separation."
            },
            {
                title: "AI Priority and Lure Behaviour",
                description: "Implemented catnip lure behaviour that could override the AI's focus on the player, allowing the lure to become a higher-priority target when encountered."
            },
            {
                title: "Player Stealth Mechanics",
                description: "Implemented player stealth features including crouching, holding breath, equipment-based sound changes, and sneak-level modifiers that affected AI detection."
            },
            {
                title: "Dynamic Hiding Interactions",
                description: "Contributed to hiding systems that allowed the player to use environment objects as stealth options during AI encounters."
            }
        ],
        technicalChallenges: [
            {
                challenge: "Creating believable stealth AI in a small prototype",
                solution: "Combined multiple detection inputs including sight, footsteps, breathing proximity, door state, and lure priority to make the AI feel reactive without requiring a large-scale AI framework.",
                result: "The prototype demonstrated a clear stealth gameplay loop where player choices affected AI detection and behaviour."
            },
            {
                challenge: "Making environmental state matter to AI behaviour",
                solution: "Implemented door-aware detection and AI door interaction logic so the cat could respond differently depending on whether rooms were accessible, visible, or acoustically connected.",
                result: "Doors became part of the stealth system instead of simple static environment props."
            }
        ],
        additionalResponsibilities: [
            "Built and arranged the prototype level environment.",
            "Worked on dynamic hiding places and interactable gameplay objects.",
            "Integrated player sneak mechanics with AI detection behaviour.",
            "Used Jira and GitHub for project tracking and collaboration."
        ],
        
        images: {
            main: 'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/PussInGardenGif.gif?raw=true',
            gallery: [
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_kY84PIrLWQ.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_9FzEsiKgtq.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_iVhLsz0muG.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_CF2vZTGajM.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/SofaHideGif.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/TableHideGif.gif?raw=true',
            ],
        },
        duration: "4 weeks",
        teamSize: "4 people",
        playUrl: "https://nihanbir.itch.io/horpus",
        githubUrl: "https://github.com/nihanbir/horpus"
    },
    {
        id: "3",
        title: "Algorithms & Data Structures",
        technologies: ["Unity", "C#", "C++", "Github"],
        shortDescription: "The key feature of this project is the implementation of a modified BFS algorithm in Unity using C#.",
        role: ["Gameplay Programmer"],
        fullDescription:
        
            "In addition to the pathfinding game, this repository features;\n" +
            "• My first experience with C++ 😊\n" +
            "• A TicTacToe game developed in C++\n" +
            "• Exercises and my learning journey in Algorithms & Data Structures\n" +
            "✨ The key feature of this project is the implementation of a modified BFS algorithm. " +
            "You can find details on the problem it addresses and its solution below. ✨\n" +
            
            "Problem: \n"+
            "In a grid of size NxM, there are K obstacles placed randomly. Each obstacle has a weight associated with it, " +
            "which is a positive integer. The task is to find the path from the bottom-right corner to top-left corner that passes " +
            "through the obstacles with the minimum total weight.\n" +
            "However, there is a catch - when the player pass through an obstacle, its weight is added to a running sum. If the running " +
            "sum becomes greater than a threshold value T, the player is teleported back to the bottom-right corner, and must start over.\n" +
            "To make the problem more interesting, the teleportation threshold T is not constant - it changes every time you get teleported. " +
            "Specifically, after being teleported, the new threshold value is set to be the sum of the weights of the obstacles the player passed " +
            "through on their previous attempt, multiplied by a constant C. At the start, T is always smaller than the sum of weights of the smallest " +
            "weight path to enforce at least one teleportation.\n" +
            
            "The goal: \n"+
            "The goal is to find the path that minimizes the sum of the weights of the obstacles the player passes through, while taking into " +
            "account the random placement of the obstacles and the changing teleportation threshold. When the goal can't be reached with the " +
            "smallest weight path, the optimal thing for the player to do, would be to expand T maximally by taking the biggest weight path. " +
            "To solve the problem of finding the biggest weight path, a case which swaps the objective of the algorithm can be added.\n"+
            
            "How I solved it:\n"+
            "Initially thought algorithm was Dijkstra however it didn't solve the problem of collecting the heighest " +
            "weight when there was no path to the goal.\n" +
            "A modified version of BFS algorithm was used to solve this problem. " +
            "BFS stores copies of all paths (when predecessor method isn't used), " +
            "therefore this seemed like the best option because all paths needed to be compared " +
            "to each other to know which one reached the highest weight when the goal wasn't reachable.\n" +
            "Modified BFS was made to take weight into account and to look at all ways to get to any given tile, not just the fastest.",

        images: {
            main:'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/991542_265422.png?raw=true',
            gallery: [
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/838013_524424.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/63067_769622.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/56604_920108.png?raw=true',
            ],
        },
        codeSnippets: [
            {
                title: "Pathfinding, Path.cs",
                language: "csharp",
                code: `using System.Collections.Generic;

public struct Path
{
    public State[] States;
    public readonly HashSet<State> VisitedStates;
    public int TotalCost;

    public Path(State[] states, HashSet<State> visitedStates, int totalCost)
    {
        States = states;
        VisitedStates = visitedStates;
        TotalCost = totalCost;
    }
}`
            },
            {
                title: "Pathfinding, Pathfinder.cs",
                language: "csharp",
                code: `using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using Utils;

public static class Pathfinder
{
    public static IEnumerable<State> BreadthFirstModified(State start, State end)
    {
        
        // make a queue of paths
        Queue<Path> todoPaths = new();
        
        // make a dictionary for paths, using the TotalCost for that path as a key
        Dictionary<int, Path> finalizedPaths = new();
        
        // start off by making a new path out of the start state, where it considers itself visited
        var startPath = new Path(new[] { start }, new HashSet<State> { start }, Game.CurrentCost);
        
        todoPaths.Enqueue(startPath);
        
        while (todoPaths.Count > 0)
        {
            Path currentPath = todoPaths.Dequeue();
            State currNode = currentPath.States[^1];
            
            // loop over all adjacent states
            foreach (var neighbor in currNode.GetSuccessors())
            {
                // neighbor already visited in this path, continue
                if (currentPath.VisitedStates.Contains(neighbor) || neighbor.Grid.GetCell(neighbor.playerPosition).visited) continue;
                
                // found end, append the neighbor and return path

                if (neighbor.Equals(end))
                {
                    return currentPath.States.Skip(1).Concat(new[] { neighbor }).ToArray();
                }

                // get the cost of the neighbor cell
                var cellCost = neighbor.Grid.GetCell(neighbor.playerPosition).cost;
                
                // create a clone clone the path as a new path
                Path newPath = new Path(currentPath.States, new HashSet<State>(currentPath.VisitedStates), currentPath.TotalCost);
                
                // append the neighbor state to the end of the new path
                newPath.States = newPath.States.Concat(new[] { neighbor }).ToArray();

                newPath.VisitedStates.Add(neighbor);
                
                // add neighbour cell's cost to path's total cost
                newPath.TotalCost += cellCost;
                
                // go to next iteration
                if (newPath.TotalCost > Game.Threshold) finalizedPaths.TryAdd(newPath.TotalCost, newPath);
                else todoPaths.Enqueue(newPath);
            }
        }
        // no paths left to dequeue, and we didnt find the goal.
        // loop over the finalizedPaths list, and return the path with the highest cost
        
        int maxCost = 0;
        foreach (var keyValuePair in finalizedPaths) maxCost = Math.Max(keyValuePair.Key, maxCost);
        return finalizedPaths[maxCost].States.Skip(1).ToArray();
    }
}`
            },
        ],
        
        githubUrl: "https://github.com/nihanbir/algorithms-and-datastructures-nihanbir"
    },
    {
        id: "4",
        title: "Klicker",
        technologies: ["SDL", "C++"],
        shortDescription: "Simple clicker game made to learn and utilize design patterns and advanced C++ features.",
        role: ["Gameplay Programmer"],
        fullDescription:

            "The game is made with SDL using;\n" +
            "• Design Patterns:\n" +
            "  • State design pattern \n" +
            "Each door is independent of each other and has 2 states, open and closed. " +
            "This pattern helps make the game scalable if you want to increase the complexity. (eg. LockedDoorState)\n" +
            "  • Update design pattern\n" +
            "Since every door is independent of each other, it makes sense for each door " +
            "to update their own state instead of listing all the updates in the main loop. This pattern also helps making the game scalable.\n" +
            "• Advanced C++ Features:\n" +
            "  • Vectors\n" +
            "For scalable collection of the doors.\n" +
            "It solves the problem of making it easier to scale the amount of functional doors in the future.\n" +
            "  • Runtime polymorphism\n" +
            "To change the state of the doors.\n" +
            "Required by the state design pattern.\n",
            

        images: {
            main: 'https://user-images.githubusercontent.com/112477158/232321356-97aa747b-8f79-432d-9434-2f6d56157326.gif',
            gallery: [            ],
        },
        githubUrl: "https://github.com/nihanbir/cpp-game-nihanbir",
        
        codeSnippets: [ 
            {
            title: "ClosedDoorState.cpp",
            language: "c++",
            code: `#include "Door.h"
#include "ClosedDoorState.h"
#include "OpenDoorState.h"

ClosedDoorState::ClosedDoorState(Door& door) {
\timage = make_unique<Image>(door.images[1]);
}

unique_ptr<DoorState> ClosedDoorState::update(const SDL_Event& e, Door& door, Window& window) {
\tif (e.type != SDL_MOUSEBUTTONDOWN) return nullptr;
\tif (!door.isHovered()) return nullptr;
\t// show image
\twindow.render(image.get(), &door.rect);
\treturn make_unique<OpenDoorState>(door);
}`
        },
            {
                title: "Door.cpp",
                language: "c++",
                code: `#include "Door.h"
#include "ClosedDoorState.h"

bool gameOver = false;

using namespace std;

Door::Door(SDL_Rect doorRect, const char* closedDoorImg, const char* openDoorImg) 
{
\trect = doorRect;
\timages[0] = closedDoorImg;
\timages[1] = openDoorImg;
\tstate = make_unique<ClosedDoorState>(*this);
\t
}

void Door::handleInput(const SDL_Event& e, Door& door, Window& window) {
\tunique_ptr<DoorState> newState = state->update(e, door, window);
\tif (newState != nullptr) state = move(newState);
}

bool Door::isHovered()
{
\t//Get mouse position
\tint x, y;
\tSDL_GetMouseState(&x, &y);
\t//Mouse is left of the button
\tif (x < rect.x) return false;
\t//Mouse is right of the button
\telse if (x > rect.x + rect.w) return false;
\t//Mouse above the button
\telse if (y < rect.y) return false;
\t//Mouse below the button
\telse if (y > rect.y + rect.h) return false;
\treturn true;
}`
            },
            {
                title: "Klicker.cpp",
                language: "c++",
                code: `#include "Window.h"
#include "Image.h"
#include "Door.h"
#include <vector>

//Screen dimension constants
const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 419;

SDL_Rect leftDoorRect{14,84,88,335};
SDL_Rect rightDoorRect{240,177,24,92};

vector<unique_ptr<Door>> doors{};

int main(int argc, char* args[])
{
\tWindow window{ SCREEN_WIDTH, SCREEN_HEIGHT };
\t//Start up SDL and create window
\tif (!window.wasSuccesful())
\t{
\t\tprintf("Failed to initialize!\\n");
\t\treturn -1;
\t}

\tdoors.push_back(make_unique<Door>(leftDoorRect, "img/DoorL_Closed.bmp", "img/DoorL_Open.bmp"));
\tdoors.push_back(make_unique<Door>(rightDoorRect, "img/DoorR_Closed.bmp", "img/DoorR_Open.bmp"));

\t//Load media
\tauto image = make_unique<Image>("img/main.bmp");
\t
\twindow.render(image.get(),nullptr);

\t//Hack to get window to stay up
\tSDL_Event e;
\twhile (!gameOver) {
\t\twhile (SDL_PollEvent(&e)) {
\t\t\tif (e.type == SDL_QUIT) return 0;
\t\t\tfor (auto& door : doors)
\t\t\t{
\t\t\t\tdoor->handleInput(e, *door, window);
\t\t\t}
\t\t}
\t}
\treturn 0;
}`
            },
        
        ]
    },
    {
        id: "5",
        title: "Slappy Knut",
        technologies: ["Unity", "C#", "Trello", "Github"],
        shortDescription: "My first unity project with a team",
        role: ["Product Owner", "Gameplay Programmer"],
        teamSize: "6 people",
        duration: "6 weeks",
        
        fullDescription:

            "Responsibilities:\n" +
            "• Structuring the project by creating, enforcing and updating UML and TDD\n" +
            "• Managing trello\n" +
            "• Implementing interfaces\n" +
            "• Merging into main branch and solving merge issues\n" +
            "• Reviewing code\n" +
            "• Bug fixing\n" +
            "• Character control\n" +
            "• Melee attack system\n" +
            "• Spells and spell casting\n" +
            "• Equippable and consumable items\n",

        images: {
            main: 'https://user-images.githubusercontent.com/112477158/212632090-9adf0583-a11c-4198-88a6-4189920c985c.png',
            gallery: [
                'https://user-images.githubusercontent.com/112477158/212632269-e50b693f-d1a6-42f1-b699-1dc163485bc4.png',
                'https://user-images.githubusercontent.com/112477158/212632343-92c39cc8-7e57-48a7-9467-bb6fbf1ebd47.png',
                'https://user-images.githubusercontent.com/112477158/212632367-3788053c-b001-483c-9b20-081faedac5ea.png',
                'https://user-images.githubusercontent.com/112477158/212632395-d1e8bdee-cb99-42ab-8c47-ce81fc761476.png',
                'https://user-images.githubusercontent.com/112477158/212632505-3e6ac2f0-99ae-40c0-af3a-9be5f57fdd09.png',
                'https://user-images.githubusercontent.com/112477158/212632415-c08fbf0d-1703-4a8a-9a05-36b72161cb50.png',
                'https://user-images.githubusercontent.com/112477158/212632567-b7131667-6648-4659-857e-980947e35621.png',
                'https://user-images.githubusercontent.com/112477158/212632536-c452fc4d-6c99-463c-a1c0-d93e6cfa9c1d.png',
                'https://user-images.githubusercontent.com/112477158/212632434-69f39a58-b7b2-4e22-9188-741bf215c008.png'
            ],
        },
        githubUrl: "https://github.com/nihanbir/slappy-knut"
    },
    {
        id: "6",
        title: "sk8escape",
        technologies: ["Unity", "C#", "Jira", "Github", "Firebase", "Google Play Console"],
        shortDescription: "This is a mobile game for Android, unfortunately it's not available to download anymore",
        role: ["Backend"],
        teamSize: "17 people",
        duration: "4 weeks",
        fullDescription:
            "This was my only backend experience—I single-handedly implemented the entire backend, and it was challenging yet quite fun. " +
            "I was also all over the project to fix bugs and review code.\n"+
            "Responsibilities:\n" +
            "• Implementation of the backend using Firebase, including analytics, online data storage, and authentication via Google Play Games.\n" +
            "• Structuring the project by creating UML and TDD.\n" +
            "• Working on solving issues from different departments.\n" +
            "• Bug fixing for various departments.\n" +
            "• Reviewing code.\n" +
            "• Assistance with publishing the game using Google Play Console.\n" +
            "• UI regarding backend.\n",

        images: {
            main: 'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/sk8escape/229985_328099.png?raw=true',
            gallery: [
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/sk8escape/132728_76860.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/sk8escape/740937_527491.gif?raw=true',
            ],
        },
        githubUrl: "https://github.com/nihanbir/Mirror-sk8escape",
        codeSnippets:[
            {
                title: "LoadManager.cs",
                language: "csharp",
                code: `using System;
using System.Collections;
using System.IO;
using Firebase.Auth;
using Firebase.Database;
using TMPro;
using UnityEngine;

namespace Backend.Scripts
{
    public class LoadManager : MonoBehaviour
    {
        private long onlineTimeStamp;
        private long localTimeStamp;
        private GameData onlineData;
        private SaveManager _saveManager;

        public GameObject startButton;
        public GameObject loadingText;
        public TextMeshProUGUI signinFailed;
        
        private bool OnlineDataMissing => onlineTimeStamp == 0;
        private bool LocalDataMissing => localTimeStamp == 0;
        private void Awake()
        {
            EnablePressToPlay(false);
            Invoke("HandleFailedSignin", 5);
            FirebaseDatabase.DefaultInstance.SetPersistenceEnabled(false);
            if (Application.internetReachability != NetworkReachability.NotReachable)
            {
                StartCoroutine(GetStats());
            }
            else
            {
                CancelInvoke("HandleFailedSignin");
                HandleFailedSignin();
            }
        }

        private void LoadData()
        {
            var path = Application.persistentDataPath + "/stats.save.json";
            GameData localData = null;
        
            if (File.Exists(path))
            {
                string json = File.ReadAllText(path);
                localData = JsonUtility.FromJson<GameData>(json);
                localTimeStamp = localData.timeStamp;
            }

            if (LocalDataMissing && OnlineDataMissing)
            {
                EnablePressToPlay(true);
                return;
            }
            //get the most up to date data stats
            SetData(localTimeStamp > onlineTimeStamp ? localData : onlineData);
        }

        private void SetData(GameData data)
        {
            SaveManager.SaveTotalScore = data.totalScore;
            SaveManager.SaveTotalGems = data.totalGems;
            SaveManager.SaveTotalCoins = data.totalCoins;
            SaveManager.SaveHighScore = data.playerHighScore;
            EnablePressToPlay(true);
        }

        //upon finish loading
        private void EnablePressToPlay(bool b)
        {
            loadingText.SetActive(!b);
            startButton.SetActive(b);
        }

        //get online stats
        public IEnumerator GetStats()
        {
            //give time to fetch
            yield return new WaitForSeconds(1);
            string username = String.Empty;
#if UNITY_ANDROID
            username = GooglePlayGames.PlayGamesPlatform.Instance.localUser.userName;
#endif
            if(username == String.Empty) username = FirebaseAuth.DefaultInstance.CurrentUser.UserId;
            var userData = FirebaseDatabase.DefaultInstance.RootReference.Child("users").Child(username).GetValueAsync();
            
            yield return new WaitUntil(predicate: () => userData.IsCompleted);

            DataSnapshot snapshot = userData.Result;
            //if online data exists
            if (snapshot != null && snapshot.Exists)
            {
                onlineData = JsonUtility.FromJson<GameData>(snapshot.GetRawJsonValue());
                onlineTimeStamp = onlineData.timeStamp;
            }
            CancelInvoke("HandleFailedSignin");
            LoadData();
        }

        void HandleFailedSignin()
        {
            signinFailed.text += "Failed to fetch online data.";
            LoadData();
            EnablePressToPlay(true);
        }
    }
}`
            },
            {
                title: "LoginPlaystore.cs",
                language: "csharp",
                code: `using System;
using System.Threading.Tasks;
using Firebase.Auth;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine;

namespace Backend.Scripts
{
    public class LoginPlayStore : MonoBehaviour
    {
        void Start()
        {
#if UNITY_ANDROID
            
            PlayGamesPlatform.DebugLogEnabled = true;
            PlayGamesPlatform.Activate();
            PlayGamesPlatform.Instance.Authenticate(ProcessAutomaticAuth);
            if (!PlayGamesPlatform.Instance.IsAuthenticated() 
                && FirebaseAuth.DefaultInstance.CurrentUser.UserId == String.Empty)
            {
                FirebaseAuth.DefaultInstance
                    .SignInAnonymouslyAsync()
                    .ContinueWith(ContinueWithLogin);
            }
#else
                
if (FirebaseAuth.DefaultInstance.CurrentUser.UserId == String.Empty){
FirebaseAuth auth = FirebaseAuth.DefaultInstance;
auth.SignInAnonymouslyAsync().ContinueWith(ContinueWithLogin);} 
            
#endif
        }
#if UNITY_ANDROID

        private static void ProcessAutomaticAuth(SignInStatus status)
        {
            if (status != SignInStatus.Success)
            {
                PlayGamesPlatform.Instance.ManuallyAuthenticate(ProcessManualAuth);
            }
            else
            {
                ProcessManualAuth(status);
            }
        }

        private static void ProcessManualAuth(SignInStatus status)
        {
            if (status != SignInStatus.Success) return;

            PlayGamesPlatform.Instance.RequestServerSideAccess(true, code =>
            {
                FirebaseAuth auth = FirebaseAuth.DefaultInstance;
                Credential credential = PlayGamesAuthProvider.GetCredential(code);
                auth.SignInWithCredentialAsync(credential).ContinueWith(ContinueWithLogin);
            });
        }
#endif
        private static void ContinueWithLogin(Task<FirebaseUser> task)
        {
                if (task.IsCanceled) Debug.Log("cancelled");
                else if (task.IsFaulted)
                {
                    Debug.Log("error" + task.Exception);
                }
                else
                {
                    FirebaseUser newUser = task.Result;
                } 
        }
        
    }
}`
            },
            
        ]
    },
];

// Extract all unique technologies from projects
export const getAllTechnologies = (): string[] => {
    return Array.from(
        new Set(
            projects.flatMap((project) => project.technologies)
        )
    );
};
