import { Project } from "@/data/index.ts";

// Project data
export const projects: Project[] = [
    {
        id: "1",
        title: "Cloven Blade",
        technologies: [
            "Unreal Engine 5",
            "C++",
            "GAS",
            "Jira",
            "Confluence",
            "GitHub",
            "Perforce",
        ],

        shortDescription:
            "A side-scrolling beat 'em up vertical slice developed at Ballistic Pork, where I served as Primary Gameplay Programmer and Scrum Master.",

        role: [
            "Primary Gameplay Programmer",
            "Scrum Master",
        ],

        teamSize: "Approximately 6 developers",

        overview:
            "Cloven Blade is a side-scrolling beat 'em up vertical slice developed in Unreal Engine 5. As Primary Gameplay Programmer, I owned the implementation of the project's gameplay layer in C++, translating gameplay design requirements into scalable technical systems while integrating animation, audio, physics, UI, AI, and Gameplay Ability System functionality. Alongside gameplay programming, I also served as Scrum Master throughout development.",

        keyTakeaways: [
            "C++ Gameplay Programming",
            "Gameplay Ability System",
            "Gameplay Architecture",
            "AI Programming",
            "Developer Tooling",
        ],

        systemsImplemented: [
            "Character controller including movement, jumping, coyote jump, dashing, hook mechanics, wall running, wall jumping, wall dashing, and edge grabbing",
            "Combat systems including attacks, combos, weapons, gameplay abilities, invincibility, and immunity",
            "Enemy AI including patrol, combat, attack behaviour, ranged enemies, upper-body aiming, and gameplay object interactions",
            "Gameplay Ability System integration",
            "Inventory system with reusable item objects",
            "Interactables including pickups, hiding barrels, smoke bombs, and shurikens",
            "Gameplay collision and combat state management",
            "Animation, audio, physics, particle effect, and UI integration",
            "Developer tooling for animation-driven gameplay events",
        ],

        technicalHighlights: [
            {
                title: "Gameplay Systems",
                description:
                    "Owned the implementation of the gameplay layer in C++, translating gameplay design requirements into scalable technical systems. Implemented player mechanics, combat, AI, Gameplay Ability System integration, interactables, inventory, gameplay state management, and reusable gameplay frameworks while supporting rapid iteration throughout development.",
            },
            {
                title: "Character Movement Systems",
                description:
                    "Implemented a modular character controller supporting movement, jumping, coyote jump, dashing, hook mechanics, wall running, wall jumping, wall dashing, and edge grabbing. Solved gameplay edge cases such as preventing infinite wall jumps while maintaining responsive player controls.",
            },
            {
                title: "Template Method Pattern",
                description:
                    "Implemented shared character behaviour through a common base character class while allowing derived character types to customize specific gameplay actions through inheritance. This provided a consistent gameplay flow while making it straightforward to extend the system with new player and AI behaviours.",
            },
            {
                title: "Observer Pattern",
                description:
                    "Implemented event-driven communication between reusable gameplay components to reduce coupling and allow gameplay systems to react to state changes without direct dependencies.",
            },
            {
                title: "Object Pool Pattern",
                description:
                    "Implemented object pooling for inventory items by recycling object instances instead of repeatedly allocating and destroying them, reducing runtime allocations while providing a reusable foundation for gameplay objects.",
            },
            {
                title: "Animation-driven Gameplay Framework",
                description:
                    "Developed reusable animation tooling that enabled gameplay effects and abilities to be activated and deactivated through configurable animation frame windows. Gameplay events generated by these windows could also be observed independently by other gameplay systems through event-driven communication, providing a flexible foundation for attacks, hit detection, invincibility, abilities, and other time-sensitive gameplay mechanics.",
            },
            {
                title: "Gameplay System Integration",
                description:
                    "Integrated artist-created animations, audio, UI, particle effects, and gameplay assets into Unreal Engine, ensuring new content functioned correctly within gameplay systems while collaborating closely with artists and designers throughout development.",
            },
        ],

        technicalChallenges: [
            {
                challenge: "Multiple project restarts and changing technical direction",
                solution:
                    "The project was restarted several times and transitioned from a pure C++ architecture to Lyra before ultimately adopting a Gameplay Ability System-based solution. I continuously adapted and reimplemented gameplay systems to support the project's evolving technical direction while maintaining development momentum.",
                result:
                    "Despite multiple architectural changes, the team successfully delivered the vertical slice with a maintainable gameplay framework that supported continued feature development.",
            },
            {
                challenge: "Supporting complex gameplay interactions",
                solution:
                    "Designed and implemented gameplay state handling for collisions, invincibility, immunity, AI interactions, animation timing, and movement edge cases while developing reusable tooling for animation-driven gameplay events.",
                result:
                    "Gameplay systems behaved consistently across a wide variety of combat and movement scenarios while reducing repetitive implementation work and improving iteration speed during development.",
            },
        ],

        additionalResponsibilities: [
            "Served as Scrum Master throughout development, facilitating daily stand-ups, sprint planning, and production tracking in Jira.",
            "Coordinated communication between programmers, artists, designers, management, and external consultants.",
            "Integrated artist-created animations, audio, UI, particle effects, and environment assets into gameplay systems.",
            "Helped maintain team alignment and delivery throughout multiple project restarts and changing technical direction.",
        ],
        images: {
            main: 'https://impro.usercontent.one/appid/oneComWsb/domain/ballisticpork.se/media/ballisticpork.se/onewebmedia/banner_clovenblade_hamlet_01.png?etag=W%2F%22745ba-678b87d4%22&sourceContentType=image%2Fpng&ignoreAspectRatio&resize=1178%2B578',
            gallery: [            ],
        },
        // videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    },
    {
        id: "2",
        title: "Horpus",
        technologies: ["Unreal Engine 5", "Blueprints", "Jira", "GitHub"],
        shortDescription: "A cute horror prototype focused on stealth gameplay, cat AI behaviour, and interactable hiding systems.",
        role: ["Gameplay Programmer"],
        overview: "Horpus is a cute horror prototype built in Unreal Engine 5 using Blueprints. As Gameplay Programmer, I focused on the cat AI, player stealth mechanics, interactable hiding and lure systems, and the environment supporting the prototype's stealth gameplay loop.",
        keyTakeaways: [
            "AI Behaviour",
            "Stealth Gameplay",
            "Interactable Systems",
            "Blueprints",
            "Level Design"
        ],
        systemsImplemented: [
            "Cat AI behaviour including investigation, pursuit, and player tracking",
            "Door interaction logic for AI, including opening doors when investigating the player or following player movement",
            "Sound-based detection for player footsteps when doors are open",
            "Breathing detection based on proximity and line-of-sight limitations",
            "Player stealth mechanics including crouching, holding breath, sneak level, and equipment-based sound modifiers",
            "Dynamic hiding interactions",
            "Interactable lure system using catnip to redirect AI priority",
            "Level layout and environment setup for the prototype"
        ],
        technicalHighlights: [
            {
                title: "AI Behaviour System",
                description: "Implemented cat AI behaviour that could investigate the player's location, react to player movement, open doors, and transition between detection and pursuit behaviours."
            },
            {
                title: "Sound-based Detection",
                description: "Built stealth detection logic where the AI could hear player footsteps depending on environmental conditions, such as whether a door was left open."
            },
            {
                title: "Proximity-based Breathing Detection",
                description: "Implemented breathing detection where the AI could detect the player at close range while respecting walls and spatial separation."
            },
            {
                title: "AI Priority and Lure Behaviour",
                description: "Implemented catnip lure behaviour that could override the AI's focus on the player, allowing the lure to become a higher-priority target when encountered."
            },
            {
                title: "Player Stealth Mechanics",
                description: "Implemented player stealth features including crouching, holding breath, equipment-based sound changes, and sneak-level modifiers that affected AI detection."
            },
            {
                title: "Dynamic Hiding Interactions",
                description: "Contributed to hiding systems that allowed the player to use environment objects as stealth options during AI encounters."
            }
        ],
        technicalChallenges: [
            {
                challenge: "Creating believable stealth AI in a small prototype",
                solution: "Combined multiple detection inputs including sight, footsteps, breathing proximity, door state, and lure priority to make the AI feel reactive without requiring a large-scale AI framework.",
                result: "The prototype demonstrated a clear stealth gameplay loop where player choices affected AI detection and behaviour."
            },
            {
                challenge: "Making environmental state matter to AI behaviour",
                solution: "Implemented door-aware detection and AI door interaction logic so the cat could respond differently depending on whether rooms were accessible, visible, or acoustically connected.",
                result: "Doors became part of the stealth system instead of simple static environment props."
            }
        ],
        additionalResponsibilities: [
            "Built and arranged the prototype level environment.",
            "Worked on dynamic hiding places and interactable gameplay objects.",
            "Integrated player sneak mechanics with AI detection behaviour.",
            "Used Jira and GitHub for project tracking and collaboration."
        ],
        
        images: {
            main: 'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/PussInGardenGif.gif?raw=true',
            gallery: [
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_kY84PIrLWQ.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_9FzEsiKgtq.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_iVhLsz0muG.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/UnrealEditor_CF2vZTGajM.png?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/SofaHideGif.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/horpus/TableHideGif.gif?raw=true',
            ],
        },
        duration: "4 weeks",
        teamSize: "4 people",
        playUrl: "https://nihanbir.itch.io/horpus",
        githubUrl: "https://github.com/nihanbir/horpus"
    },
    {
        id: "3",
        title: "Algorithms & Data Structures",
        technologies: ["Unity", "C#", "C++", "GitHub"],
        shortDescription: "A pathfinding and algorithms project featuring a modified BFS solution for weighted grid traversal with changing constraints.",
        role: ["Gameplay Programmer"],
        overview: "This project explores algorithms and data structures through a Unity pathfinding challenge and smaller C++ exercises. The main challenge was finding a route through a weighted grid whose traversal threshold changes between attempts: the search must minimize cost when the goal is reachable, but select the highest-cost reachable fallback when it is not.",
        keyTakeaways: [
            "Algorithm Design",
            "Modified BFS",
            "Pathfinding",
            "C#",
            "C++ Practice"
        ],
        systemsImplemented: [
            "Modified BFS pathfinding algorithm",
            "Weighted grid traversal",
            "State-based path representation",
            "Path cost evaluation",
            "Fallback path selection when the goal is unreachable",
            "TicTacToe game in C++",
            "Algorithms and data structures exercises"
        ],
        technicalHighlights: [
            {
                title: "Modified BFS Pathfinding",
                description: "Implemented a modified Breadth-First Search algorithm that evaluates weighted paths through a grid while tracking accumulated cost and changing traversal constraints."
            },
            {
                title: "State-based Path Representation",
                description: "Represented each path as a sequence of states with its own visited-state collection and total cost, allowing multiple possible routes to the same tile to be evaluated instead of only keeping the first discovered path."
            },
            {
                title: "Dynamic Objective Handling",
                description: "Handled cases where the goal could not be reached under the current threshold by selecting the highest-cost reachable path to expand the next attempt's threshold, rather than simply failing the search."
            },
            {
                title: "Algorithm Tradeoffs",
                description: "Used path copying to preserve full route information for comparison, accepting higher memory usage in exchange for simpler path evaluation and support for the project's changing objective."
            },
            {
                title: "C++ Fundamentals",
                description: "Practiced C++ through smaller exercises including a TicTacToe implementation while building foundational understanding of algorithms and data structures."
            }
        ],
        technicalChallenges: [
            {
                challenge: "Standard shortest-path assumptions did not fit the problem",
                solution: "Dijkstra-style thinking was not enough because the algorithm sometimes needed to maximize path cost when the goal could not be reached, then minimize cost once the threshold allowed completion.",
                result: "A modified BFS approach allowed the search to evaluate multiple routes and switch behaviour depending on whether the goal was reachable."
            },
            {
                challenge: "Comparing complete candidate paths",
                solution: "Stored full path copies with visited states and total cost so paths could be compared directly when deciding whether to return a successful route or the highest-cost fallback route.",
                result: "The algorithm could evaluate both successful and failed attempts while preserving enough information to choose an appropriate path."
            }
        ],
        additionalResponsibilities: [
            "Documented the problem, attempted approaches, and final solution.",
            "Included code snippets to demonstrate the data structures and search implementation.",
            "Used the project to build confidence with both C# algorithm implementation and C++ fundamentals."
        ],

        images: {
            main:'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/991542_265422.png?raw=true',
            gallery: [
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/838013_524424.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/63067_769622.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/algorithms/56604_920108.png?raw=true',
            ],
        },
        codeSnippets: [
            {
                title: "Pathfinding, Path.cs",
                language: "csharp",
                code: `using System.Collections.Generic;

public struct Path
{
    public State[] States;
    public readonly HashSet<State> VisitedStates;
    public int TotalCost;

    public Path(State[] states, HashSet<State> visitedStates, int totalCost)
    {
        States = states;
        VisitedStates = visitedStates;
        TotalCost = totalCost;
    }
}`
            },
            {
                title: "Pathfinding, Pathfinder.cs",
                language: "csharp",
                code: `using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using Utils;

public static class Pathfinder
{
    public static IEnumerable<State> BreadthFirstModified(State start, State end)
    {
        
        // make a queue of paths
        Queue<Path> todoPaths = new();
        
        // make a dictionary for paths, using the TotalCost for that path as a key
        Dictionary<int, Path> finalizedPaths = new();
        
        // start off by making a new path out of the start state, where it considers itself visited
        var startPath = new Path(new[] { start }, new HashSet<State> { start }, Game.CurrentCost);
        
        todoPaths.Enqueue(startPath);
        
        while (todoPaths.Count > 0)
        {
            Path currentPath = todoPaths.Dequeue();
            State currNode = currentPath.States[^1];
            
            // loop over all adjacent states
            foreach (var neighbor in currNode.GetSuccessors())
            {
                // neighbor already visited in this path, continue
                if (currentPath.VisitedStates.Contains(neighbor) || neighbor.Grid.GetCell(neighbor.playerPosition).visited) continue;
                
                // found end, append the neighbor and return path

                if (neighbor.Equals(end))
                {
                    return currentPath.States.Skip(1).Concat(new[] { neighbor }).ToArray();
                }

                // get the cost of the neighbor cell
                var cellCost = neighbor.Grid.GetCell(neighbor.playerPosition).cost;
                
                // create a clone clone the path as a new path
                Path newPath = new Path(currentPath.States, new HashSet<State>(currentPath.VisitedStates), currentPath.TotalCost);
                
                // append the neighbor state to the end of the new path
                newPath.States = newPath.States.Concat(new[] { neighbor }).ToArray();

                newPath.VisitedStates.Add(neighbor);
                
                // add neighbour cell's cost to path's total cost
                newPath.TotalCost += cellCost;
                
                // go to next iteration
                if (newPath.TotalCost > Game.Threshold) finalizedPaths.TryAdd(newPath.TotalCost, newPath);
                else todoPaths.Enqueue(newPath);
            }
        }
        // no paths left to dequeue, and we didnt find the goal.
        // loop over the finalizedPaths list, and return the path with the highest cost
        
        int maxCost = 0;
        foreach (var keyValuePair in finalizedPaths) maxCost = Math.Max(keyValuePair.Key, maxCost);
        return finalizedPaths[maxCost].States.Skip(1).ToArray();
    }
}`
            },
        ],
        
        githubUrl: "https://github.com/nihanbir/algorithms-and-datastructures-nihanbir"
    },
    {
        id: "4",
        title: "Klicker",
        technologies: ["SDL", "C++"],
        shortDescription: "A small SDL/C++ clicker game built to practice design patterns, runtime polymorphism, and ownership with smart pointers.",
        role: ["Gameplay Programmer"],
        overview: "Klicker is a small SDL/C++ clicker game built as a focused architecture exercise. Its interactive doors provided a compact gameplay context for practicing the State pattern, runtime polymorphism, container-based object handling, and explicit ownership with smart pointers.",
        keyTakeaways: [
            "C++",
            "SDL",
            "State Pattern",
            "Runtime Polymorphism",
            "Smart Pointers"
        ],
        systemsImplemented: [
            "Interactive clickable doors",
            "Independent door state handling",
            "Open and closed door states",
            "Mouse hover detection",
            "Input-driven state transitions",
            "Door collection using vectors",
            "Object ownership using unique_ptr"
        ],
        technicalHighlights: [
            {
                title: "State Pattern",
                description: "Implemented each door using separate open and closed states, allowing door behaviour to change based on its current state while keeping transition logic organized and extensible."
            },
            {
                title: "Runtime Polymorphism",
                description: "Used polymorphic door state classes to allow doors to transition between behaviours at runtime without hard-coding every state case inside the main game loop."
            },
            {
                title: "Smart Pointer Ownership",
                description: "Used unique_ptr to express ownership of door objects and door states, reducing manual memory management while practicing modern C++ patterns."
            },
            {
                title: "Scalable Door Handling",
                description: "Stored doors in a vector so new interactive doors could be added without changing the main input loop structure."
            },
            {
                title: "Input-driven Interaction",
                description: "Implemented mouse position checks and click handling so each door could independently determine whether it should react to player input."
            }
        ],
        technicalChallenges: [
            {
                challenge: "Avoiding hard-coded door logic",
                solution: "Moved door behaviour into state classes so each door could handle its own transitions instead of managing all door cases directly in the main loop.",
                result: "The project became easier to extend with additional door states such as locked or animated doors."
            },
            {
                challenge: "Practicing safe ownership in C++",
                solution: "Used unique_ptr for doors and state transitions to make ownership clear and reduce reliance on manual allocation and deletion.",
                result: "The project provided practical experience with modern C++ ownership patterns in a small gameplay context."
            }
        ],
        additionalResponsibilities: [
            "Built the project as a focused C++ practice exercise.",
            "Used SDL for rendering, input handling, and window management.",
            "Created code snippets demonstrating the door state system and input-driven update loop."
        ],

        images: {
            main: 'https://user-images.githubusercontent.com/112477158/232321356-97aa747b-8f79-432d-9434-2f6d56157326.gif',
            gallery: [            ],
        },
        githubUrl: "https://github.com/nihanbir/cpp-game-nihanbir",
        
        codeSnippets: [ 
            {
            title: "ClosedDoorState.cpp",
            language: "c++",
            code: `#include "Door.h"
#include "ClosedDoorState.h"
#include "OpenDoorState.h"

ClosedDoorState::ClosedDoorState(Door& door) {
\timage = make_unique<Image>(door.images[1]);
}

unique_ptr<DoorState> ClosedDoorState::update(const SDL_Event& e, Door& door, Window& window) {
\tif (e.type != SDL_MOUSEBUTTONDOWN) return nullptr;
\tif (!door.isHovered()) return nullptr;
\t// show image
\twindow.render(image.get(), &door.rect);
\treturn make_unique<OpenDoorState>(door);
}`
        },
            {
                title: "Door.cpp",
                language: "c++",
                code: `#include "Door.h"
#include "ClosedDoorState.h"

bool gameOver = false;

using namespace std;

Door::Door(SDL_Rect doorRect, const char* closedDoorImg, const char* openDoorImg) 
{
\trect = doorRect;
\timages[0] = closedDoorImg;
\timages[1] = openDoorImg;
\tstate = make_unique<ClosedDoorState>(*this);
\t
}

void Door::handleInput(const SDL_Event& e, Door& door, Window& window) {
\tunique_ptr<DoorState> newState = state->update(e, door, window);
\tif (newState != nullptr) state = move(newState);
}

bool Door::isHovered()
{
\t//Get mouse position
\tint x, y;
\tSDL_GetMouseState(&x, &y);
\t//Mouse is left of the button
\tif (x < rect.x) return false;
\t//Mouse is right of the button
\telse if (x > rect.x + rect.w) return false;
\t//Mouse above the button
\telse if (y < rect.y) return false;
\t//Mouse below the button
\telse if (y > rect.y + rect.h) return false;
\treturn true;
}`
            },
            {
                title: "Klicker.cpp",
                language: "c++",
                code: `#include "Window.h"
#include "Image.h"
#include "Door.h"
#include <vector>

//Screen dimension constants
const int SCREEN_WIDTH = 640;
const int SCREEN_HEIGHT = 419;

SDL_Rect leftDoorRect{14,84,88,335};
SDL_Rect rightDoorRect{240,177,24,92};

vector<unique_ptr<Door>> doors{};

int main(int argc, char* args[])
{
\tWindow window{ SCREEN_WIDTH, SCREEN_HEIGHT };
\t//Start up SDL and create window
\tif (!window.wasSuccesful())
\t{
\t\tprintf("Failed to initialize!\\n");
\t\treturn -1;
\t}

\tdoors.push_back(make_unique<Door>(leftDoorRect, "img/DoorL_Closed.bmp", "img/DoorL_Open.bmp"));
\tdoors.push_back(make_unique<Door>(rightDoorRect, "img/DoorR_Closed.bmp", "img/DoorR_Open.bmp"));

\t//Load media
\tauto image = make_unique<Image>("img/main.bmp");
\t
\twindow.render(image.get(),nullptr);

\t//Hack to get window to stay up
\tSDL_Event e;
\twhile (!gameOver) {
\t\twhile (SDL_PollEvent(&e)) {
\t\t\tif (e.type == SDL_QUIT) return 0;
\t\t\tfor (auto& door : doors)
\t\t\t{
\t\t\t\tdoor->handleInput(e, *door, window);
\t\t\t}
\t\t}
\t}
\treturn 0;
}`
            },
        
        ]
    },
    {
        id: "5",
        title: "Slappy Knut",
        technologies: ["Unity", "C#", "Trello", "GitHub"],
        shortDescription: "My first team-based Unity project, where I worked on character control, combat, spells, items, project structure, and production coordination.",
        role: ["Product Owner", "Gameplay Programmer"],
        teamSize: "6 people",
        duration: "6 weeks",
        overview: "Slappy Knut was my first team-based Unity project. As Gameplay Programmer, I implemented core character, combat, spell, and item functionality in C#. I also served as Product Owner, helping organize the project's technical structure and coordinate production across the team.",
        keyTakeaways: [
            "Unity Gameplay",
            "C#",
            "Combat Systems",
            "Interfaces",
            "Team Collaboration"
        ],
        systemsImplemented: [
            "Character control",
            "Melee attack system",
            "Spell casting system",
            "Equippable items",
            "Consumable items",
            "Gameplay interfaces",
            "Bug fixes across gameplay systems",
            "Project structure documentation using UML and TDD"
        ],
        technicalHighlights: [
            {
                title: "Character Control",
                description: "Implemented player character control and core gameplay input, providing the foundation for movement and combat interactions."
            },
            {
                title: "Melee Combat System",
                description: "Implemented melee attack functionality and integrated it with the player character, supporting direct combat interactions."
            },
            {
                title: "Spell Casting System",
                description: "Implemented spell casting behaviour and connected it with the character's gameplay actions."
            },
            {
                title: "Item Systems",
                description: "Worked on equippable and consumable item functionality, allowing gameplay items to affect the player during combat and exploration."
            },
            {
                title: "Interface-based Gameplay Structure",
                description: "Implemented gameplay interfaces to keep systems more modular and easier to extend across different item, spell, and character behaviours."
            },
            {
                title: "Code Review and Merge Support",
                description: "Reviewed code, merged work into the main branch, resolved merge issues, and helped maintain a stable team codebase."
            }
        ],
        technicalChallenges: [
            {
                challenge: "Keeping a first team project organized",
                solution: "Created, enforced, and updated UML and TDD documentation while helping structure the project and coordinate implementation across the team.",
                result: "The team had clearer technical direction and a more organized foundation for collaboration."
            },
            {
                challenge: "Maintaining stability across shared gameplay code",
                solution: "Handled merges into the main branch, resolved merge conflicts, reviewed code, and fixed bugs across gameplay systems.",
                result: "The project remained more stable while multiple team members contributed to the same codebase."
            }
        ],
        additionalResponsibilities: [
            "Served as Product Owner during the project.",
            "Managed the Trello board and production tasks.",
            "Created, enforced, and updated UML and TDD documentation.",
            "Reviewed code and helped resolve merge issues.",
            "Contributed bug fixes across different parts of the project."
        ],

        images: {
            main: 'https://user-images.githubusercontent.com/112477158/212632090-9adf0583-a11c-4198-88a6-4189920c985c.png',
            gallery: [
                'https://user-images.githubusercontent.com/112477158/212632269-e50b693f-d1a6-42f1-b699-1dc163485bc4.png',
                'https://user-images.githubusercontent.com/112477158/212632343-92c39cc8-7e57-48a7-9467-bb6fbf1ebd47.png',
                'https://user-images.githubusercontent.com/112477158/212632367-3788053c-b001-483c-9b20-081faedac5ea.png',
                'https://user-images.githubusercontent.com/112477158/212632395-d1e8bdee-cb99-42ab-8c47-ce81fc761476.png',
                'https://user-images.githubusercontent.com/112477158/212632505-3e6ac2f0-99ae-40c0-af3a-9be5f57fdd09.png',
                'https://user-images.githubusercontent.com/112477158/212632415-c08fbf0d-1703-4a8a-9a05-36b72161cb50.png',
                'https://user-images.githubusercontent.com/112477158/212632567-b7131667-6648-4659-857e-980947e35621.png',
                'https://user-images.githubusercontent.com/112477158/212632536-c452fc4d-6c99-463c-a1c0-d93e6cfa9c1d.png',
                'https://user-images.githubusercontent.com/112477158/212632434-69f39a58-b7b2-4e22-9188-741bf215c008.png'
            ],
        },
        githubUrl: "https://github.com/nihanbir/slappy-knut"
    },
    {
        id: "6",
        title: "sk8escape",
        technologies: ["Unity", "C#", "Jira", "Github", "Firebase", "Google Play Console"],
        shortDescription: "This is a mobile game for Android, unfortunately it's not available to download anymore",
        role: ["Backend"],
        teamSize: "17 people",
        duration: "4 weeks",
        fullDescription:
            "This was my only backend experience—I single-handedly implemented the entire backend, and it was challenging yet quite fun. " +
            "I was also all over the project to fix bugs and review code.\n"+
            "Responsibilities:\n" +
            "• Implementation of the backend using Firebase, including analytics, online data storage, and authentication via Google Play Games.\n" +
            "• Structuring the project by creating UML and TDD.\n" +
            "• Working on solving issues from different departments.\n" +
            "• Bug fixing for various departments.\n" +
            "• Reviewing code.\n" +
            "• Assistance with publishing the game using Google Play Console.\n" +
            "• UI regarding backend.\n",

        images: {
            main: 'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/sk8escape/229985_328099.png?raw=true',
            gallery: [
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/sk8escape/132728_76860.gif?raw=true',
                'https://github.com/nihanbir/portfolio-website/blob/main/src/media/projects/sk8escape/740937_527491.gif?raw=true',
            ],
        },
        githubUrl: "https://github.com/nihanbir/Mirror-sk8escape",
        codeSnippets:[
            {
                title: "LoadManager.cs",
                language: "csharp",
                code: `using System;
using System.Collections;
using System.IO;
using Firebase.Auth;
using Firebase.Database;
using TMPro;
using UnityEngine;

namespace Backend.Scripts
{
    public class LoadManager : MonoBehaviour
    {
        private long onlineTimeStamp;
        private long localTimeStamp;
        private GameData onlineData;
        private SaveManager _saveManager;

        public GameObject startButton;
        public GameObject loadingText;
        public TextMeshProUGUI signinFailed;
        
        private bool OnlineDataMissing => onlineTimeStamp == 0;
        private bool LocalDataMissing => localTimeStamp == 0;
        private void Awake()
        {
            EnablePressToPlay(false);
            Invoke("HandleFailedSignin", 5);
            FirebaseDatabase.DefaultInstance.SetPersistenceEnabled(false);
            if (Application.internetReachability != NetworkReachability.NotReachable)
            {
                StartCoroutine(GetStats());
            }
            else
            {
                CancelInvoke("HandleFailedSignin");
                HandleFailedSignin();
            }
        }

        private void LoadData()
        {
            var path = Application.persistentDataPath + "/stats.save.json";
            GameData localData = null;
        
            if (File.Exists(path))
            {
                string json = File.ReadAllText(path);
                localData = JsonUtility.FromJson<GameData>(json);
                localTimeStamp = localData.timeStamp;
            }

            if (LocalDataMissing && OnlineDataMissing)
            {
                EnablePressToPlay(true);
                return;
            }
            //get the most up to date data stats
            SetData(localTimeStamp > onlineTimeStamp ? localData : onlineData);
        }

        private void SetData(GameData data)
        {
            SaveManager.SaveTotalScore = data.totalScore;
            SaveManager.SaveTotalGems = data.totalGems;
            SaveManager.SaveTotalCoins = data.totalCoins;
            SaveManager.SaveHighScore = data.playerHighScore;
            EnablePressToPlay(true);
        }

        //upon finish loading
        private void EnablePressToPlay(bool b)
        {
            loadingText.SetActive(!b);
            startButton.SetActive(b);
        }

        //get online stats
        public IEnumerator GetStats()
        {
            //give time to fetch
            yield return new WaitForSeconds(1);
            string username = String.Empty;
#if UNITY_ANDROID
            username = GooglePlayGames.PlayGamesPlatform.Instance.localUser.userName;
#endif
            if(username == String.Empty) username = FirebaseAuth.DefaultInstance.CurrentUser.UserId;
            var userData = FirebaseDatabase.DefaultInstance.RootReference.Child("users").Child(username).GetValueAsync();
            
            yield return new WaitUntil(predicate: () => userData.IsCompleted);

            DataSnapshot snapshot = userData.Result;
            //if online data exists
            if (snapshot != null && snapshot.Exists)
            {
                onlineData = JsonUtility.FromJson<GameData>(snapshot.GetRawJsonValue());
                onlineTimeStamp = onlineData.timeStamp;
            }
            CancelInvoke("HandleFailedSignin");
            LoadData();
        }

        void HandleFailedSignin()
        {
            signinFailed.text += "Failed to fetch online data.";
            LoadData();
            EnablePressToPlay(true);
        }
    }
}`
            },
            {
                title: "LoginPlaystore.cs",
                language: "csharp",
                code: `using System;
using System.Threading.Tasks;
using Firebase.Auth;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using UnityEngine;

namespace Backend.Scripts
{
    public class LoginPlayStore : MonoBehaviour
    {
        void Start()
        {
#if UNITY_ANDROID
            
            PlayGamesPlatform.DebugLogEnabled = true;
            PlayGamesPlatform.Activate();
            PlayGamesPlatform.Instance.Authenticate(ProcessAutomaticAuth);
            if (!PlayGamesPlatform.Instance.IsAuthenticated() 
                && FirebaseAuth.DefaultInstance.CurrentUser.UserId == String.Empty)
            {
                FirebaseAuth.DefaultInstance
                    .SignInAnonymouslyAsync()
                    .ContinueWith(ContinueWithLogin);
            }
#else
                
if (FirebaseAuth.DefaultInstance.CurrentUser.UserId == String.Empty){
FirebaseAuth auth = FirebaseAuth.DefaultInstance;
auth.SignInAnonymouslyAsync().ContinueWith(ContinueWithLogin);} 
            
#endif
        }
#if UNITY_ANDROID

        private static void ProcessAutomaticAuth(SignInStatus status)
        {
            if (status != SignInStatus.Success)
            {
                PlayGamesPlatform.Instance.ManuallyAuthenticate(ProcessManualAuth);
            }
            else
            {
                ProcessManualAuth(status);
            }
        }

        private static void ProcessManualAuth(SignInStatus status)
        {
            if (status != SignInStatus.Success) return;

            PlayGamesPlatform.Instance.RequestServerSideAccess(true, code =>
            {
                FirebaseAuth auth = FirebaseAuth.DefaultInstance;
                Credential credential = PlayGamesAuthProvider.GetCredential(code);
                auth.SignInWithCredentialAsync(credential).ContinueWith(ContinueWithLogin);
            });
        }
#endif
        private static void ContinueWithLogin(Task<FirebaseUser> task)
        {
                if (task.IsCanceled) Debug.Log("cancelled");
                else if (task.IsFaulted)
                {
                    Debug.Log("error" + task.Exception);
                }
                else
                {
                    FirebaseUser newUser = task.Result;
                } 
        }
        
    }
}`
            },
            
        ]
    },
];

// Extract all unique technologies from projects
export const getAllTechnologies = (): string[] => {
    return Array.from(
        new Set(
            projects.flatMap((project) => project.technologies)
        )
    );
};
